export default function Head() {
  return (
    <>
      <title>MilesStone Grill</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link type="image/png" sizes="16x16" rel="icon" href="/icons8-restaurant-16.png" />
    </>
  );
}
